version: '3.5'

services:
  postgres-odoo-base-15-01:
    container_name: postgres_odoo-base-15-01
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      PGDATA: /data/postgres
    volumes:
       - /home/ttdn/ttdn_k15/database_ttdn/cntt15_01_db/_data:/data/postgres
    ports:
      - "5431:5432"
    # networks:
    #   - postgres
    # restart: unless-stopped

  odoo:
    container_name: odoo_app
    build: .
    depends_on:
      - postgres-odoo-base-15-01
    environment:
      HOST: postgres-odoo-base-15-01
      PORT: 5432
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      DB_NAME: ${POSTGRES_DB:-odoo}
    ports:
      - "8069:8069"
    volumes:
      - /home/quang/TTDN-15-01-N1/addons:/mnt/extra-addons
      - /home/quang/TTDN-15-01-N1:/home/quang/TTDN-15-01-N1
      - odoo_filestore:/var/lib/odoo/filestore
    restart: unless-stopped
    command: odoo --addons-path=/mnt/extra-addons --database=${POSTGRES_DB:-odoo} --db_user=${POSTGRES_USER:-odoo} --db_password=${POSTGRES_PASSWORD:-odoo} --db_host=postgres-odoo-base-15-01

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - pgadmin:/root/.pgadmin

  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

#networks:
#  postgres:
#    driver: bridge

volumes:
  odoo_filestore:
#    postgres:
#    pgadmin:
